version: 2

builds:
  - binary: govm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w -X main.build={{.Version}}
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true


brews:
  -
    name: govm

    homepage: https://github.com/emmadal/govm

    commit_author:
      name: emmadal
      email: emmanueldalougou@gmail.com

    description: A tool to manage Go versions

    license: MIT

checksum:
  name_template: 'checksums.txt'
