builds:
  - binary: govm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: govm
    homepage: https://github.com/emmadal/govm
    commit_author:
      name: emmadal
      email: emmanueldalougou@gmail.com

checksum:
  name_template: 'checksums.txt'