builds:
  - binary: govm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - name: govm
    replace: true

brews:
  - name: govm
    homepage: https://github.com/emmadal/govm
    tap:
      owner: emmadal
      name: govm
    commit_author:
      name: emmadal
      email: emmanueldalougou@gmail.com

checksum:
  name_template: 'checksums.txt'
